name: SolMobile CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      
      - name: Run tests
        run: |
          xcodebuild test \
            -scheme SolMobile \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -project ios/SolMobile/SolMobile.xcodeproj
